### ISSUE TITLE
docker run give this error 

### ISSUE THREAD

**Issue by katewang0710** [udacity/CarND-Term1-Starter-Kit#105]
docker run -it --rm --entrypoint "/run.sh" -p 8888:8888 -v `pwd`:/src starter-kit
[I 06:00:54.232 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/carnd-term1/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by mvirgo** [comment]
Hi Kate - 

Thanks for letting us know about this issue. You should use the classroom workspaces in the meantime, or if you must utilize a local environment, you should also try the anaconda environment set-up. We'll look into what the issue with the docker file is.

**Comment by mvirgo** [comment]
I think [this PR](https://github.com/udacity/CarND-Term1-Starter-Kit/pull/106) has fixed the main item here (ValueError: '' does not appear to be an IPv4 or IPv6 address), although I'll keep open for further investigation.

**Comment by mvirgo** [comment]
It otherwise looks like that PR has fixed this issue. Please let me know if you try to `docker pull` it again and it still does not work!
