### ISSUE TITLE
Error installing keras on macOS Sierra

### ISSUE THREAD

**Issue by ejstembler** [udacity/CarND-Term1-Starter-Kit#80]
After issuing 

`sh
conda env create -f environment.yml
`

It fails when it gets to keras:

<pre>
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/ejstembler/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Users/ejstembler/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/Users/ejstembler/.local/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Users/ejstembler/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 74, in <module>
    import appdirs
ImportError: No module named 'appdirs'

CondaValueError: pip returned an error.
</pre>

This is on macOS Sierra, version 10.12.5 (16F73)

I also tried replacing <tt>- keras==1.2.1</tt> with <tt>- git+https://github.com/fchollet/keras.git</tt> in [environment.yml](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment.yml); same error.

**Comment by domluna** [comment]
@ejstembler haven't run into this one before. Which version of the conda installer are you using?

**Comment by mvirgo** [comment]
No recent responses, so I'll close this out, but the error would indicate the need to `pip install appdirs`.
