### ISSUE TITLE
create carnd-term1 failed on AWS EC2

### ISSUE THREAD

**Issue by XQ-UT** [udacity/CarND-Term1-Starter-Kit#88]
carnd@ip-172-31-31-197:~/CarND-Term1-Starter-Kit$ conda env create -f environment-gpu.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........
Linking packages ...
Traceback (most recent call last):##################################################################################   |  97%
  File "/home/carnd/anaconda3/envs/carnd-term1/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/home/carnd/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/carnd/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
LinkError: Link error: Error: post-link failed for: menpo::widgetsnbextension-1.2.3-py35_1

**Comment by mvirgo** [comment]
The current AMI should have the necessary libraries installed; closing.
